version: "3.9"

services:
  fastapi-demo:
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  ngrok:
    image: ngrok/ngrok
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
      - NGROK_REGION=ap
    command: http fastapi-demo:8000
    depends_on:
      - fastapi-demo
    ports:
      - "4040:4040"
